import csv
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass

@dataclass
class Song:
    """
    Represents a song and its attributes.
    Required by tests/test_recommender.py
    """
    id: int
    title: str
    artist: str
    genre: str
    mood: str
    energy: float
    tempo_bpm: float
    valence: float
    danceability: float
    acousticness: float

@dataclass
class UserProfile:
    """
    Represents a user's taste preferences.
    Required by tests/test_recommender.py
    """
    favorite_genre: str
    favorite_mood: str
    target_energy: float
    likes_acoustic: bool
    target_tempo: Optional[float] = None

taste_profile = UserProfile(
    favorite_genre="rock",
    favorite_mood="intense",   # randomly chosen
    target_energy=0.65,
    likes_acoustic=False,      # randomly chosen
    target_tempo=140,          # randomly chosen (bpm)
)

class Recommender:
    """
    OOP implementation of the recommendation logic.
    Required by tests/test_recommender.py

    This class implements the same Algorithm Recipe as score_song() /
    recommend_songs() below, but works directly with Song/UserProfile
    dataclasses instead of dicts. The scoring math is intentionally
    duplicated here rather than shared with the functional API: the two
    APIs take different inputs (dataclasses vs. dicts), and converting
    between them on every call would add coupling and overhead for a
    scoring formula this small. Keeping them independent makes each API
    simple to read and explain on its own, at the cost of ~20 lines of
    repeated logic.
    """
    def __init__(self, songs: List[Song]):
        self.songs = songs

    def _score(self, user: UserProfile, song: Song) -> Tuple[float, List[str]]:
        """
        Scores a single Song against a UserProfile using the Algorithm
        Recipe (weighted genre match, mood match, and energy/tempo/
        acousticness closeness). Mirrors score_song()'s logic.

        Returns (score, reasons) where score is 0-1 and reasons is a
        list of human-readable strings explaining what drove the score.
        """
        reasons: List[str] = []
        score = 0.0

        genre_match = song.genre.lower() == user.favorite_genre.lower()
        if genre_match:
            score += GENRE_WEIGHT
            reasons.append(f"matches your favorite genre ({song.genre})")

        mood_match = song.mood.lower() == user.favorite_mood.lower()
        if mood_match:
            score += MOOD_WEIGHT
            reasons.append(f"matches your favorite mood ({song.mood})")

        energy_closeness = 1 - min(abs(song.energy - user.target_energy), 1.0)
        score += ENERGY_WEIGHT * energy_closeness
        if energy_closeness >= 0.85:
            reasons.append(f"energy ({song.energy}) is close to what you want ({user.target_energy})")

        # Tempo preference is optional - only score it if the user stated one.
        if user.target_tempo is not None:
            tempo_distance = abs(song.tempo_bpm - user.target_tempo)
            tempo_closeness = 1 - min(tempo_distance / TEMPO_RANGE, 1.0)
            score += TEMPO_WEIGHT * tempo_closeness
            if tempo_closeness >= 0.85:
                reasons.append(f"tempo ({song.tempo_bpm} bpm) is close to what you want ({user.target_tempo} bpm)")

        if user.likes_acoustic:
            score += ACOUSTIC_WEIGHT * song.acousticness
            if song.acousticness >= 0.6:
                reasons.append("has an acoustic feel you tend to like")
        else:
            score += ACOUSTIC_WEIGHT * (1 - song.acousticness)
            if song.acousticness <= 0.3:
                reasons.append("has the non-acoustic energy you tend to like")

        if not reasons:
            reasons.append("a decent overall match on your preferences")

        return score, reasons

    def recommend(self, user: UserProfile, k: int = 5) -> List[Song]:
        """
        Returns the top k Song records for this user.

        Applies our Ranking Rule: score every song with _score(), sort
        by score descending (tie-break by song id ascending for a
        deterministic order), then take the top k.
        """
        scored = [(song, self._score(user, song)[0]) for song in self.songs]
        scored.sort(key=lambda pair: (-pair[1], pair[0].id))
        return [song for song, _ in scored[:k]]

    def explain_recommendation(self, user: UserProfile, song: Song) -> str:
        """
        Returns a human-readable, semicolon-separated explanation of
        why `song` was recommended to `user`, built from the reasons
        generated by _score().
        """
        _, reasons = self._score(user, song)
        return "; ".join(reasons)

INTEGER_FIELDS = {"id"}
FLOAT_FIELDS = {"energy", "tempo_bpm", "valence", "danceability", "acousticness"}

def load_songs(csv_path: str) -> List[Dict]:
    """
    Loads songs from a CSV file.
    Required by src/main.py

    Reads the file with csv.DictReader, which turns every row into a
    dict of column_name -> string value. Since every value from a CSV
    starts out as a string, the fields listed in INTEGER_FIELDS and
    FLOAT_FIELDS are converted to their numeric types so later scoring
    math (e.g. energy_closeness) can operate on real numbers instead
    of text.
    """
    songs: List[Dict] = []
    with open(csv_path, newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            song = dict(row)
            for field in INTEGER_FIELDS:
                song[field] = int(song[field])
            for field in FLOAT_FIELDS:
                song[field] = float(song[field])
            songs.append(song)
    return songs

# Weights from our finalized Algorithm Recipe (see README "How The System
# Works"). They sum to 1.0 so a perfect-match song scores exactly 1.0.
GENRE_WEIGHT = 0.35
MOOD_WEIGHT = 0.25
ENERGY_WEIGHT = 0.20
TEMPO_WEIGHT = 0.10
ACOUSTIC_WEIGHT = 0.10

# tempo_bpm isn't naturally on a 0-1 scale like the other features, so we
# normalize its distance against an assumed realistic range (ballad to
# drum & bass) before it can be combined with the other components.
TEMPO_MIN = 40
TEMPO_MAX = 200
TEMPO_RANGE = TEMPO_MAX - TEMPO_MIN

def score_song(user_prefs: Dict, song: Dict) -> Tuple[float, List[str]]:
    """
    Scores a single song against user preferences.
    Required by recommend_songs() and src/main.py

    Implements the Algorithm Recipe: a weighted sum of a genre match,
    a mood match, and how close the song's energy/tempo/acousticness
    are to what the user wants. Each numeric feature uses a "closeness"
    formula (1 - normalized distance) so being near the target scores
    well, not just being high or low.

    user_prefs keys used: genre, mood, energy, tempo (optional),
    likes_acoustic (optional, default False).

    Returns (score, reasons) where score is 0-1 and reasons is a list
    of human-readable strings explaining what drove the score, so the
    caller can build an explanation for the user.
    """
    reasons: List[str] = []
    score = 0.0

    genre_match = song.get("genre", "").lower() == user_prefs.get("genre", "").lower()
    if genre_match:
        score += GENRE_WEIGHT
        reasons.append(f"matches your favorite genre ({song.get('genre')})")

    mood_match = song.get("mood", "").lower() == user_prefs.get("mood", "").lower()
    if mood_match:
        score += MOOD_WEIGHT
        reasons.append(f"matches your favorite mood ({song.get('mood')})")

    energy = float(song.get("energy", 0.0))
    target_energy = float(user_prefs.get("energy", 0.0))
    energy_closeness = 1 - min(abs(energy - target_energy), 1.0)
    score += ENERGY_WEIGHT * energy_closeness
    if energy_closeness >= 0.85:
        reasons.append(f"energy ({energy}) is close to what you want ({target_energy})")

    # Tempo preference is optional - only score it if the user stated one.
    target_tempo = user_prefs.get("tempo")
    if target_tempo is not None:
        tempo_bpm = float(song.get("tempo_bpm", 0.0))
        tempo_distance = abs(tempo_bpm - float(target_tempo))
        tempo_closeness = 1 - min(tempo_distance / TEMPO_RANGE, 1.0)
        score += TEMPO_WEIGHT * tempo_closeness
        if tempo_closeness >= 0.85:
            reasons.append(f"tempo ({tempo_bpm} bpm) is close to what you want ({target_tempo} bpm)")

    acousticness = float(song.get("acousticness", 0.0))
    likes_acoustic = user_prefs.get("likes_acoustic", False)
    if likes_acoustic:
        score += ACOUSTIC_WEIGHT * acousticness
        if acousticness >= 0.6:
            reasons.append("has an acoustic feel you tend to like")
    else:
        score += ACOUSTIC_WEIGHT * (1 - acousticness)
        if acousticness <= 0.3:
            reasons.append("has the non-acoustic energy you tend to like")

    if not reasons:
        reasons.append("a decent overall match on your preferences")

    return score, reasons

def recommend_songs(user_prefs: Dict, songs: List[Dict], k: int = 5) -> List[Tuple[Dict, float, str]]:
    """
    Functional implementation of the recommendation logic.
    Required by src/main.py

    Applies our Ranking Rule: score every song, sort by score descending
    (tie-break by song id ascending for a deterministic order), then take
    the top k. Each result includes a human-readable explanation built
    from score_song's reasons, joined with "; " so callers can split the
    string back into individual reasons for display (e.g. as bullets).
    """
    scored = [(song, *score_song(user_prefs, song)) for song in songs]
    scored.sort(key=lambda entry: (-entry[1], entry[0].get("id", 0)))

    return [
        (song, score, "; ".join(reasons))
        for song, score, reasons in scored[:k]
    ]
